CREATE TABLE roles (id INTEGER PRIMARY KEY, name VARCHAR(10) NOT NULL UNIQUE);
CREATE TABLE statuses (id INTEGER PRIMARY KEY, name VARCHAR(15) NOT NULL UNIQUE);
CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login VARCHAR(15) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  first_name VARCHAR(20) NOT NULL,
  last_name VARCHAR(20) NOT NULL,
  register_date TIMESTAMP NOT NULL,
  login_date TIMESTAMP,
  credentials_changed_at TIMESTAMP,
  status_id INTEGER NOT NULL,
  role_id INTEGER NOT NULL
);
CREATE TABLE subjects (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(25) NOT NULL UNIQUE
);
CREATE TABLE levels (id INTEGER PRIMARY KEY, level VARCHAR(10) NOT NULL);
CREATE TABLE quizzes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  time_to_pass INTEGER NOT NULL,
  level_id INTEGER NOT NULL,
  subject_id INTEGER NOT NULL
);
CREATE TABLE questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question VARCHAR(250) NOT NULL,
  quiz_id INTEGER NOT NULL
);
CREATE TABLE answers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answer VARCHAR(50) NOT NULL,
  correct BOOLEAN NOT NULL,
  question_id INTEGER NOT NULL
);
CREATE TABLE attempts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  score INTEGER NOT NULL,
  start_time TIMESTAMP NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  end_time TIMESTAMP,
  completed BOOLEAN NOT NULL,
  quiz_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL
);
-- The foreign key is here because production has it, and its absence hid a
-- real failure: a completion that inserts a result for an answer the
-- administrator has deleted passes against a schema without it and violates
-- fk_results_answer against the schema V2 actually builds.
CREATE TABLE results (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  answer_id INTEGER NOT NULL,
  attempt_id INTEGER NOT NULL,
  CONSTRAINT uq_results_attempt_answer UNIQUE (attempt_id, answer_id),
  CONSTRAINT fk_results_answer FOREIGN KEY (answer_id) REFERENCES answers (id) ON DELETE CASCADE
);
CREATE TABLE attempt_questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id INTEGER NOT NULL,
  question_id INTEGER NOT NULL,
  question_text VARCHAR(250) NOT NULL,
  answer_id INTEGER NOT NULL,
  answer_text VARCHAR(50) NOT NULL,
  correct BOOLEAN NOT NULL,
  CONSTRAINT uq_attempt_questions_attempt_answer UNIQUE (attempt_id, answer_id)
);
