plugins {
    id 'base'
    id 'org.sonarqube' version '7.3.1.8318'
}

group = 'ua.nure.latysh'
version = '1.0-SNAPSHOT'

sonar {
    properties {
        property 'sonar.projectKey', 'vitaliilatysh_quizproject'
        property 'sonar.organization', 'vitaliilatysh'
        property 'sonar.gradle.scanAll', 'true'
        property 'sonar.qualitygate.wait', 'true'
        property 'sonar.coverage.jacoco.xmlReportPaths',
                'api/build/reports/jacoco/test/jacocoTestReport.xml'
        property 'sonar.exclusions', 'api/src/main/resources/db/migration/**/*.sql'
    }
}

tasks.named('sonar') {
    dependsOn ':api:jacocoTestReport'
}
