spring:
  application:
    name: quiz-api
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tests_db?characterEncoding=UTF-8&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1

server:
  port: ${API_PORT:8081}
  error:
    include-message: never

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
