apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../backend
images:
  - name: quiz-api
    newName: ghcr.io/vitaliilatysh/quizproject
    newTag: master
patches:
  - path: deployment-patch.yaml
