apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-account.yaml
  - config-map.yaml
  - deployment.yaml
  - service.yaml
  - pod-disruption-budget.yaml
images:
  - name: quiz-api
    newName: ghcr.io/vitaliilatysh/quizproject-api
    newTag: latest
