apiVersion: v1
kind: ServiceAccount
metadata:
  name: quiz-api
  namespace: quizproject
  labels:
    app.kubernetes.io/name: quiz-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: quizproject
automountServiceAccountToken: false
